// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo5BTz1HtLY2HliSnCe4LH2KP3zObD_Io',
    appId: '1:681725404328:web:310f0f26150dfe35f0ce9d',
    messagingSenderId: '681725404328',
    projectId: 'modul13-8502b',
    authDomain: 'modul13-8502b.firebaseapp.com',
    storageBucket: 'modul13-8502b.firebasestorage.app',
    measurementId: 'G-ELFKFKZ488',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVyevJzvCMzblpn4WRbYzcLzOJZR6mEHA',
    appId: '1:681725404328:android:0b9e6841482c4a08f0ce9d',
    messagingSenderId: '681725404328',
    projectId: 'modul13-8502b',
    storageBucket: 'modul13-8502b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4Yo9G0-TTtDaKtI0dHNP5-LQjITARDxg',
    appId: '1:681725404328:ios:884b2b8592f9bba8f0ce9d',
    messagingSenderId: '681725404328',
    projectId: 'modul13-8502b',
    storageBucket: 'modul13-8502b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4Yo9G0-TTtDaKtI0dHNP5-LQjITARDxg',
    appId: '1:681725404328:ios:884b2b8592f9bba8f0ce9d',
    messagingSenderId: '681725404328',
    projectId: 'modul13-8502b',
    storageBucket: 'modul13-8502b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDo5BTz1HtLY2HliSnCe4LH2KP3zObD_Io',
    appId: '1:681725404328:web:7397106929f94285f0ce9d',
    messagingSenderId: '681725404328',
    projectId: 'modul13-8502b',
    authDomain: 'modul13-8502b.firebaseapp.com',
    storageBucket: 'modul13-8502b.firebasestorage.app',
    measurementId: 'G-TJEBJ8DLQK',
  );
}
