// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5pcnS8-DCssY5UvYCyWjwMSaTYlRwDFE',
    appId: '1:493186596386:web:e5c4c43580df600a1c147b',
    messagingSenderId: '493186596386',
    projectId: 'modul12-fbe26',
    authDomain: 'modul12-fbe26.firebaseapp.com',
    storageBucket: 'modul12-fbe26.firebasestorage.app',
    measurementId: 'G-DSZX5YLTR8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8hTHetMlmYJ339M3pXD2BnLunpKQBWJY',
    appId: '1:493186596386:android:81dcadb17f4a78a51c147b',
    messagingSenderId: '493186596386',
    projectId: 'modul12-fbe26',
    storageBucket: 'modul12-fbe26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7oKaIupxuL7rbdEs82GTzss95qSNtdFc',
    appId: '1:493186596386:ios:3696d797b39179cc1c147b',
    messagingSenderId: '493186596386',
    projectId: 'modul12-fbe26',
    storageBucket: 'modul12-fbe26.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7oKaIupxuL7rbdEs82GTzss95qSNtdFc',
    appId: '1:493186596386:ios:3696d797b39179cc1c147b',
    messagingSenderId: '493186596386',
    projectId: 'modul12-fbe26',
    storageBucket: 'modul12-fbe26.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5pcnS8-DCssY5UvYCyWjwMSaTYlRwDFE',
    appId: '1:493186596386:web:540b095cdef67f2d1c147b',
    messagingSenderId: '493186596386',
    projectId: 'modul12-fbe26',
    authDomain: 'modul12-fbe26.firebaseapp.com',
    storageBucket: 'modul12-fbe26.firebasestorage.app',
    measurementId: 'G-548W525Q9Y',
  );
}
